language: node_js
addons:
    code_climate:
        repo_token: $CODE_CLIMATE_TOKEN
node_js:
  - "6"
  - "10"

install:
  - npm install

before_script:
  - npm install -g mocha

after_success:
  - npm run cover
  - codeclimate-test-reporter < coverage/lcov.info

deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"